### PR TITLE
Expose storage adapter option

### PR DESCRIPTION
**Pull request by wtrocki**
Implementation for #7 

## Motivation 
Expose storage adapter option.

- [x] Add option to set custom handler.
- [x] Update type definitions
- [x] Bump version
- [x] Verification
- [x] Release

### CODE REVIEW

**Review by emilioicai — APPROVED** [review]
LGTM

**Comment by wtrocki** [comment]
@emilioicai This still require some minor improvements as mentioned above.

**Comment by emilioicai** [comment]
@wtrocki what do you mean by 'improve interface'? Is that something I can pick up?

**Comment by wtrocki** [comment]
I will take care of the stuff that needs to be done.

**Pull request merged**
