### PR TITLE
fixing to work along with IOS 12 webkit update

### PR DESCRIPTION
**Pull request by chandu177**
I guess it will help in getting a fix to work along with IOS 12 webkit update.

index db close
https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/close

close index db connection 
https://www.w3.org/TR/IndexedDB-2/#database-connection

more info on closing connection 
https://www.w3.org/TR/IndexedDB-2/#closing-connection

Errors to know -
INVALID_STATE_ERR - 

Webkit change - 
https://github.com/WebKit/webkit/commit/d76f1810d09d7628105dc20e69a344f7132bf137#diff-9cbed35d828e4e5dae83da502324292aR47

Webkit raised exception when connection was not properly close before. 
` UnknownError, "Connection to Indexed Database server lost. Refresh the page to try again`

### CODE REVIEW

**Comment by camilamacedo86** [comment]
HI @chandu177,

Thank you for your contribution. Could you please add in the first comment the following PR template with all infos?

----
## Motivation
Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 

## What
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)

## Why
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)

## How
Add an short answer for: How it was done? (E.g By removing this feature from ... OR By removing just the button but not its implementation ... ) 

## Verification Steps
Add the steps required to check this change. Following an example.
 
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the users. 
 ----

**Comment by wtrocki** [comment]
Verified on IOS12. 
This PR fixes indexed db storage for IOS 12.

**Comment by camilamacedo86** [comment]
Hi @wtrocki, 

Did you check if after this change the previous and supported versions still working as well? 

@austincunningham I think is important you beware of it since you are the route this week.

**Comment by camilamacedo86** [comment]
We are accepting this PR.

**Pull request merged**
